### ISSUE TITLE
Add support for f-droids new repository format

### ISSUE THREAD

**Issue by bt90** [Droid-ify/client#287]
The official F-Droid client recently gained support for delta repository index updates:

https://f-droid.org/2023/03/01/new-repo-format-faster-smaller-updates.html

It would be nice if Droid-ify could also use the [entry.json](https://f-droid.org/repo/entry.json) file to speedup index updates.

**Comment by Iamlooker** [comment]
I will start working on this tomorrow.

**Comment by Iamlooker** [comment]
This is now the first priority. I will work on other topics once this is over

**Comment by grote** [comment]
Have you considered making use of the [official F-Droid libraries](https://gitlab.com/fdroid/fdroidclient/-/tree/master/libs#f-droid-libraries) for this? At least the minimal index library should be helpful.

**Comment by Iamlooker** [comment]
I looked into it but thought I will write my own implementation

**Comment by grote** [comment]
Here's an early draft of a blog post about those libraries. Maybe it can convince you to not re-invent the wheel:
https://gitlab.com/fdroid/fdroid-website/-/blob/80143c506cc4ea2f0a1cd10791760fd8457c7a2a/_posts/2023-05-15-three-client-libraries.md

**Comment by Iamlooker** [comment]
Cool I will read it and get back. But I just wanted to tell you something, your best locale selector is probably not working as intended. I wrote my own and I think it is passing all the tests that I wrote which inspired by your tests.

**Comment by Iamlooker** [comment]
@grote [this](https://github.com/Iamlooker/Droid-ify/blob/e501c69267b721d58960d838e9dfcce920b8cc92/core/database/src/main/java/com/looker/core/database/utils/Localization.kt#L14) seems to be the solution for the locale selector imo.

Also on FDroid libraries, I want to use them but they seem a little confusing and hard to integrate with my current structure but I will try it, it is harder because I will be adding support for GitHub Release soon

**Comment by grote** [comment]
> [This](https://gitlab.com/fdroid/fdroidclient/-/blob/master/libs/index/src/androidAndroidTest/kotlin/org/fdroid/BestLocaleTest.kt#L44) is one of the test which fails with the current implementation of [LocaleChooser](https://gitlab.com/fdroid/fdroidclient/-/blob/master/libs/index/src/androidMain/kotlin/org/fdroid/LocaleChooser.kt#L8)

This test seems to be copied one-to-one from F-Droid's source code (again without attribution and license declaration): 
https://gitlab.com/fdroid/fdroidclient/-/blob/680a1154cf3806390c2e4a9e95a7c6d6107b470f/libs/index/src/androidAndroidTest/kotlin/org/fdroid/BestLocaleTest.kt#L43

It is passing just fine. So maybe you were thinking of other tests that don't pass for F-Droid's locale chooser implementation?

**Comment by Iamlooker** [comment]
@grote I added credits to FDroid in latest commit [3ee1064c40d8caeac5ba5719bbd86ea6d5cd8fe0](https://github.com/Iamlooker/Droid-ify/commit/3ee1064c40d8caeac5ba5719bbd86ea6d5cd8fe0). You can tell me if anything needs to be changed

**Comment by Iamlooker** [comment]
> It is passing just fine. So maybe you were thinking of other tests that don't pass for F-Droid's locale chooser implementation?

Idk it was failing for me. I will try to replicate it can share a ss to you here

**Comment by grote** [comment]
What device do you run it on? Which Android version? Maybe there's differences on older versions.

**Comment by grote** [comment]
This is an instrumentation test. It won't work as a unit test which probably explains the failure you've been seeing. Roboelectric most likely doesn't provide the real implementation and just mocks those classes.

**Comment by Iamlooker** [comment]
> This is an instrumentation test. It won't work as a unit test which probably explains the failure you've been seeing. Roboelectric most likely doesn't provide the real implementation and just mocks those classes.

😵😵 My bad

**Comment by Idesmi** [comment]
> It still downloads whole 1.2 mb of index from izzyondroid's repo. I wonder if it's a bug or sth else.

Index v2 implementation has not been completed

**Comment by Iamlooker** [comment]
@grote There seems to be a reflection error due to mismatch in ktor library version in the `fdroid-download` and my versions. 

Maybe this can be fixed on the library side? I am encountring this issue when I add `:core:data` library to my `:app` module. The full error is:

<details>
<summary>Logs</summary>

```FATAL EXCEPTION: main
                                                                Process: com.looker.droidify.debug, PID: 14559
                                                                java.lang.ExceptionInInitializerError
                                                                	at kotlin.reflect.jvm.internal.impl.types.error.ErrorModuleDescriptor.<clinit>(ErrorModuleDescriptor.kt:23)
                                                                	at kotlin.reflect.jvm.internal.impl.types.error.ErrorUtils.<clinit>(ErrorUtils.kt:14)
                                                                	at kotlin.reflect.jvm.internal.impl.types.error.ErrorUtils.createErrorType(Unknown Source:0)
                                                                	at kotlin.reflect.jvm.internal.impl.types.TypeUtils.<clinit>(TypeUtils.java:36)
                                                                	at kotlin.reflect.jvm.internal.impl.types.TypeUtils.makeUnsubstitutedType(TypeUtils.java:213)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.impl.AbstractClassDescriptor$1.invoke(AbstractClassDescriptor.java:49)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.impl.AbstractClassDescriptor$1.invoke(AbstractClassDescriptor.java:46)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.impl.AbstractClassDescriptor.getDefaultType(AbstractClassDescriptor.java:175)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsCustomizer.createMockJavaIoSerializableType(JvmBuiltInsCustomizer.kt:91)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsCustomizer.<init>(JvmBuiltInsCustomizer.kt:59)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns$customizer$2.invoke(JvmBuiltIns.kt:76)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns$customizer$2.invoke(JvmBuiltIns.kt:75)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(storage.kt:42)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.getCustomizer(JvmBuiltIns.kt:75)
                                                                	at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava.<init>(DeserializationComponentsForJava.kt:80)
                                                                	at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJavaKt.makeDeserializationComponentsForJava(DeserializationComponentsForJava.kt:192)
                                                                	at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava$Companion.createModuleData(DeserializationComponentsForJava.kt:123)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:32)
                                                                	at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
                                                                	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:36)
                                                                	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
                                                                	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt:35)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:50)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
                                                                	at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:48)
AndroidRuntime          com.looker.droidify.debug            E  	at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:124)
                                                                	at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:128)
                                                                	at io.ktor.client.statement.HttpResponseKt.bodyAsChannel(HttpResponse.kt:101)
                                                                	at com.looker.network.KtorDownloader$downloadToFile$2.invokeSuspend(KtorDownloader.kt:76)
                                                                	at com.looker.network.KtorDownloader$downloadToFile$2.invoke(Unknown Source:8)
                                                                	at com.looker.network.KtorDownloader$downloadToFile$2.invoke(Unknown Source:4)
                                                                	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:50)
                                                                	at io.ktor.client.statement.HttpStatement$execute$1.invokeSuspend(Unknown Source:15)
                                                                	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4dcca43, Dispatchers.Main]
                                                                Caused by: java.lang.IllegalStateException: Resource not found in classpath: kotlin/kotlin.kotlin_builtins
                                                                	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createBuiltInPackageFragmentProvider(BuiltInsLoaderImpl.kt:59)
                                                                	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createPackageFragmentProvider(BuiltInsLoaderImpl.kt:35)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:105)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<init>(DefaultBuiltIns.kt:24)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<init>(DefaultBuiltIns.kt:21)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<clinit>(DefaultBuiltIns.kt:31)```

</details>

**Comment by Iamlooker** [comment]
Also I am getting the following error when I have both my `downloader` and `:core:data` in the main `:app` module.


This occurs when I try to download a file. It works fine if I dont have data module(Which contains `fdroid-download`) in my app module

<details>
<summary>Logs</summary>

```FATAL EXCEPTION: main
                                                                Process: com.looker.droidify.debug, PID: 14559
                                                                java.lang.ExceptionInInitializerError
                                                                	at kotlin.reflect.jvm.internal.impl.types.error.ErrorModuleDescriptor.<clinit>(ErrorModuleDescriptor.kt:23)
                                                                	at kotlin.reflect.jvm.internal.impl.types.error.ErrorUtils.<clinit>(ErrorUtils.kt:14)
                                                                	at kotlin.reflect.jvm.internal.impl.types.error.ErrorUtils.createErrorType(Unknown Source:0)
                                                                	at kotlin.reflect.jvm.internal.impl.types.TypeUtils.<clinit>(TypeUtils.java:36)
                                                                	at kotlin.reflect.jvm.internal.impl.types.TypeUtils.makeUnsubstitutedType(TypeUtils.java:213)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.impl.AbstractClassDescriptor$1.invoke(AbstractClassDescriptor.java:49)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.impl.AbstractClassDescriptor$1.invoke(AbstractClassDescriptor.java:46)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.impl.AbstractClassDescriptor.getDefaultType(AbstractClassDescriptor.java:175)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsCustomizer.createMockJavaIoSerializableType(JvmBuiltInsCustomizer.kt:91)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsCustomizer.<init>(JvmBuiltInsCustomizer.kt:59)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns$customizer$2.invoke(JvmBuiltIns.kt:76)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns$customizer$2.invoke(JvmBuiltIns.kt:75)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
                                                                	at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(storage.kt:42)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.getCustomizer(JvmBuiltIns.kt:75)
                                                                	at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava.<init>(DeserializationComponentsForJava.kt:80)
                                                                	at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJavaKt.makeDeserializationComponentsForJava(DeserializationComponentsForJava.kt:192)
                                                                	at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava$Companion.createModuleData(DeserializationComponentsForJava.kt:123)
                                                                	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:32)
                                                                	at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
                                                                	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:36)
                                                                	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
                                                                	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt:35)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:50)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
                                                                	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
                                                                	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
                                                                	at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:48)
AndroidRuntime          com.looker.droidify.debug            E  	at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:124)
                                                                	at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:128)
                                                                	at io.ktor.client.statement.HttpResponseKt.bodyAsChannel(HttpResponse.kt:101)
                                                                	at com.looker.network.KtorDownloader$downloadToFile$2.invokeSuspend(KtorDownloader.kt:76)
                                                                	at com.looker.network.KtorDownloader$downloadToFile$2.invoke(Unknown Source:8)
                                                                	at com.looker.network.KtorDownloader$downloadToFile$2.invoke(Unknown Source:4)
                                                                	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:50)
                                                                	at io.ktor.client.statement.HttpStatement$execute$1.invokeSuspend(Unknown Source:15)
                                                                	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4dcca43, Dispatchers.Main]
                                                                Caused by: java.lang.IllegalStateException: Resource not found in classpath: kotlin/kotlin.kotlin_builtins
                                                                	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createBuiltInPackageFragmentProvider(BuiltInsLoaderImpl.kt:59)
                                                                	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createPackageFragmentProvider(BuiltInsLoaderImpl.kt:35)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:105)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<init>(DefaultBuiltIns.kt:24)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<init>(DefaultBuiltIns.kt:21)
                                                                	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<clinit>(DefaultBuiltIns.kt:31)```

</details>

**Comment by grote** [comment]
does it work when using the same ktor library version?

**Comment by Iamlooker** [comment]
> does it work when using the same ktor library version?

Nope it still fails

**Comment by grote** [comment]
Does it work when excluding the ktor dependency from fdroid's downloader lib? is your kotlin-reflect dependency on the same kotlin version as your project?

**Comment by Iamlooker** [comment]
I am not using `kotlin-relfect`. And exclusion was not possible working (Maybe I was doing something wrong), I tried this:

`implementation(FDroid.download) { exclude("io.ktor") }`

but it was still available to use

**Comment by grote** [comment]
Your stacktrace shows that you *do* use kotlin-reflect, so please as a first thing add it as an explicit dependency and ensure that it uses the same kotlin version as your project does. This is a common source of such errors.

**Comment by Iamlooker** [comment]
> Your stacktrace shows that you _do_ use kotlin-reflect, so please as a first thing add it as an explicit dependency and ensure that it uses the same kotlin version as your project does. This is a common source of such errors.

That seems to have fixed it. I digged a little deeper and it seemed like Android Studio G comes with `kotlin version 1.8.20` and the reflect was also using the same.

Either was thanks 😄

**Comment by Iamlooker** [comment]
> ProGuard 🤔

In debug builds tho

**Comment by Ght55** [comment]
Not select text for copy

**Comment by Iamlooker** [comment]
> I am facing a similar issue again, this time I have the latest reflect and kotlin version but still.

 Btw this happens when I am downloading a v1 format index. Sorry @grote for tagging again

**Comment by grote** [comment]
`Unresolved class: class java.lang.String` looks very strange. Does it happen for all v1 indexes or only a specific one? Have you tried manually parsing the affected index and reducing it down to find the part of it causing the error?

**Comment by Iamlooker** [comment]
> `Unresolved class: class java.lang.String` looks very strange. Does it happen for all v1 indexes or only a specific one? 

Yes, it happens with Izzy and FDroid index v1.
> Have you tried manually parsing the affected index and reducing it down to find the part of it causing the error?

Removing `packages` map fixes the issue

**Comment by Iamlooker** [comment]
You can test it in [this branch](https://github.com/Droid-ify/client/tree/test-index-v1), you just need to build and click sync button on main screen

**Comment by chimbori** [comment]
Tested with repo `https://apps.chimbori.com/fdroid/repo`, but it still fails to validate the index with APK built from source from `test-index-v1`.

The repo was generated by `fdroidserver`: `stable 2.2.1` on macOS, and can be correctly parsed by the official F-Droid app.

Thank you for looking into this!

**Comment by mecuricat** [comment]
Any update on this?

**Comment by Iamlooker** [comment]
@machiav3lli As we are both working with same stuff here, should we both work on it [here](https://github.com/Droid-ify/client/tree/main/sync/fdroid)? Or are you planning to use FDroid's library completely through-and-through?

**Comment by Iamlooker** [comment]
## Only support for diff parsing is missing

Otherwise everything seems to be working the way I intend 🤔 

I will add license and other references in few day to code similar to FDroid Library.

**Comment by Iamlooker** [comment]
I would like some help with Diff Parsing to speed up the process, I won't be able to allocate any time to this for some time now.

**Comment by machiav3lli** [comment]
Started checking & navigating the codes & docs.

**Comment by machiav3lli** [comment]
@Iamlooker So, just reporting: the most complexity seems in keeping the automated parsing and still using diff. Specially considering v2 diffs, the archived versions get `null` value, which can't be handled in the current map objects. There is two easy-ish solutions:
- Either we copy f-droid's [`ReflectionDiffer.applyDiff()`](https://gitlab.com/fdroid/fdroidclient/-/blob/master/libs/index/src/androidMain/kotlin/org/fdroid/index/v2/ReflectionDiffer.kt) and maintain our fitted version.
- or we duplicate your `IndexV2`, `PackageV2` & `RepoV2` in Diff-variations were the related fields are nullable. This would keep the the objects non-nullable for external, non-indexing works.

Another (mostly implausible) option is to use F-Droid's libs, but then it'll get pretty complex adding extensions (also considering the effort you put in this). So I'll wait your opinion, we can also discuss things in a call/chat.

**Comment by Iamlooker** [comment]
@machiav3lli Thanks for going through this messy code. About automated parsing, we can switch to old school Jackson parsing if we wanted to, its just rewriting these two classes: [V1Parser](https://github.com/Droid-ify/client/blob/main/sync/fdroid/src/main/kotlin/com/looker/sync/fdroid/v1/V1Parser.kt) & [V2Parser](https://github.com/Droid-ify/client/blob/main/sync/fdroid/src/main/kotlin/com/looker/sync/fdroid/v2/V2Parser.kt)

Both the options sound good to me, but if I had to choose one it would be the second one, just duplicate the models, make some edits and its almost good to go (I am running away from reflection, they scare me now)

Also about extensions, we can simply extend these classes like ExodusSyncable or ExodusParser in future to add extensions and make them optional based on user preferences, this would be really simple as far as I can think.

You know me, my dm's are always open 😄 . We can even arrange a call at your preferable time.

**Comment by Iamlooker** [comment]
Aah and also I think switching to old school parsing will allow us to not create a so many models and just rely on some builders or something, idk. Or or or wait... **we can write our own json parser,** the **fastest** one yet using [json-schema](https://json-schema.org/) which is automated but also maps to current models and is just perfect?

NVM 😅

**Comment by machiav3lli** [comment]
@Iamlooker
> About automated parsing, we can switch to old school Jackson parsing if we wanted to, its just rewriting these two classes: [V1Parser](https://github.com/Droid-ify/client/blob/main/sync/fdroid/src/main/kotlin/com/looker/sync/fdroid/v1/V1Parser.kt) & [V2Parser](https://github.com/Droid-ify/client/blob/main/sync/fdroid/src/main/kotlin/com/looker/sync/fdroid/v2/V2Parser.kt)

Hehe, nah nah not that complicated. It's just defining Diff-Variations of the mentioned 3 classes and declaring patchers. 

> Both the options sound good to me, but if I had to choose one it would be the second one, just duplicate the models, make some edits and its almost good to go (I am running away from reflection, they scare me now)

I've already written most of the logic locally and should be able to complete it and PR it before the weekend. It seems that sync:fdroid will have to be an android.library instead of jvm.library. I actually don't mind this, as I'd need anyway another implementation for Workers.

Maybe we can in the future streamline things and make an independent lib out of this, but not for now.

> Also about extensions, we can simply extend these classes like ExodusSyncable or ExodusParser in future to add extensions and make them optional based on user preferences, this would be really simple as far as I can think.

It'd be even easier just adding the extensions to the respective serializable classes with empty/null defaults.

> Aah and also I think switching to old school parsing will allow us to not create a so many models and just rely on some builders or something, idk. Or or or wait... we can write our own json parser, the fastest one yet using [json-schema](https://json-schema.org/) which is automated but also maps to current models and is just perfect?

Actually Foxy-Droid's old-school parser is still the one used in NS, which is afair the last part of Foxy-Droid still existing in NS, but will be replaced to one using kotlinx.serialization in 1.1.0, which is part of my plan for Index-V2+. We'll talk about it in more details when I start officially working on it.

**Comment by machiav3lli** [comment]
PRed in #825

**Comment by grote** [comment]
When parsing the JSON diff as JSON, how do you differentiate a missing value from an explicit `null` using kotlinx.serialization?

**Comment by machiav3lli** [comment]
@grote I solved this in a pretty hacky way (for now), defaulting values of the duplicate classes (`Diff` as suffix) to null, and then only writing the values existing in the diff over the ones in the current index. Taking maps, lists and non-atomic-objects into account. Check the `IndexV2.kt`, `RepoV2.kt` and `PackageV2.kt` files. Mainly the `patchInto()` functions are relevant to your question.

**Comment by grote** [comment]
> I solved this in a pretty hacky way (for now), defaulting values of the duplicate classes (Diff as suffix) to null, and then only writing the values existing in the diff over the ones in the current index. 

Right, but what if an app or a version got removed by setting it to `null` in the diff. How do you differentiate non-existence from an explicit `null`? At least this bit wasn't clear to me when looking at the code.

**Comment by machiav3lli** [comment]
>  I guess for maps, you get an entry of entry(key, null),

Exactly.

> but what if the donation option of an app was removed for example?

in the current implementation it'll be kept :p (the scenario wasn't included in the diffs I tested, so it slipped through). So I guess the patchers will have to go one level deeper.

Lists are one of the things I needed more information on (and didn't find). For example what diff we get when a mirror get updated: do we get the whole list updated? or only the updated mirror? The first one would increase the size of the diff (not relevant tbh), the second will lead to conflicts on the logic of patching.

**Comment by grote** [comment]
You may want to add test cases. Please observe licensing and attribution in case you copy test cases from the official v2 libs.

**Comment by Iamlooker** [comment]
@grote cd68d0fcf0bad1eb612615875194c973e77806b6 improves performance by 3 times on old device and 2 times on newer devices on a smaller index. Improvement would be bigger on older devices and bigger index

**Comment by grote** [comment]
thanks for the heads up, so instead of strict parsing, the `PermissionV1` is just an array of strings where even number is `name` and odd number is `maxSdk`. However, this only helps with index-v1 which should only be used by some rarely updated smaller repos and only until those get latest fdroidserver eventually.

**Comment by Iamlooker** [comment]
Yes, but this could be used just to support faster conversions.

Also is there any breaking changes in new fdroidserver release, since you pointed it out

**Comment by eternaltyro** [comment]
Is this feature still being worked on?

**Comment by Iamlooker** [comment]
This feature is done, will be available after migration to Jetpack Compose is complete.

**Comment by licaon-kter** [comment]
I guess #1266 happens because of https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1604

@Iamlooker index-v2 was never merged?

**Comment by Iamlooker** [comment]
@licaon-kter Index v2 was merged but its not for legacy architecture. And UI refactoring is stuck right now because of time constraints

**Comment by Iamlooker** [comment]
+ Due to Android 15+ foreground service changes I am struggling a little bit on finalizing what I should be using

**Comment by PurpleCodingWizard** [comment]
> * Due to Android 15+ foreground service changes I am struggling a little bit on finalizing what I should be using

Have you looked at what Fdoid basic V2 Alpha and Neo store do for background jobs? They both target Android 16 and 15 respectively.

**Comment by machiav3lli** [comment]
@Iamlooker I could look at it next week and include it with the long-overdue Index-V2 Parsing update.
