### ISSUE TITLE
[Crash] cancel system installer initialization

### ISSUE THREAD

**Issue by userkilled** [Droid-ify/client#343]
**Describe the bug**
Dropped the application at the time of installation by pressing cancel at the time of package initialization, the system installer.

I upgrade VPNhood

**To Reproduce**
## 1. Go to '. https://apt.izzysoft.de/fdroid/repo/com.vpnhood.client.android_369.apk.'
2. Click on 'update'
# 3. Scroll down to 'close system installer'

FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 18332
java.lang.ArrayIndexOutOfBoundsException: length=22; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.looker.droidify.ui.app_detail.AppDetailAdapter$$ExternalSyntheticLambda5.onClick(R8$$SyntheticClass:21)
	at android.view.View.performClick(View.java:7155)
	at android.widget.CompoundButton.performClick(CompoundButton.java:142)
	at android.view.View.performClickInternal(View.java:7128)
	at android.view.View.access$3500(View.java:803)
	at android.view.View$PerformClick.run(View.java:27542)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Smartphone (please complete the following information):**
 - Device: blackview 6300pro
 - OS: android 10
 - Version 0.5.7

**Comment by Iamlooker** [comment]
This should be fixed in last few updates. You can ping me if not.
