### ISSUE TITLE
`Update all` crashes app

### ISSUE THREAD

**Issue by klaurence** [Droid-ify/client#433]
**Describe the bug**
Droid-ify crashes when you press `Update all`.

**To Reproduce**
1. Go to the `Updates` tab of the app.
2. Press the `Update all` button in the bottom-right. The app then crashes.

**Smartphone (please complete the following information):**
 - OS: Android 10
 - Version (where the crashes occur):
     - 0.5.8.1 stable
     - 0.5.8.1 debug (from commit 03addd8's built debug APK [here](https://github.com/Droid-ify/client/actions/runs/5921862029))
     - (I can't access the Telegram channel, so I can't verify this crash from APKs there.)

**Additional context**

(My phone is unfortunately not rooted, so I can't give logcats.)

<details>
<summary>Enabled repositories</summary>

- F-Droid
- F-Droid Archive
- Guardian Project Official Releases
- Guardian Project Archive
- IzzyOnDroid F-Droid Repo
- Bromite official F-Droid repository
- NewPipe upstream repository
- Bitwarden F-Droid Repo
</details>

**Comment by userkilled** [comment]
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 4777
java.lang.RuntimeException: Unable to create application com.looker.droidify.MainApplication: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6493)
	at android.app.ActivityThread.access$1400(ActivityThread.java:226)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getByName(InetAddress.java:1106)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:235)
	at com.looker.droidify.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(SourceFile:121)
	at dagger.internal.DoubleCheck.get(SourceFile:14)
	at com.looker.droidify.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.ktorDownloader(Unknown Source:4)
	at com.looker.droidify.Hilt_MainApplication.onCreate(SourceFile:39)
	at com.looker.droidify.MainApplication.onCreate(SourceFile:3)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6488)
	... 8 more
--
Is this??

**Comment by userkilled** [comment]
@klaurence i use Scoop (Catches a stack trace when an app crashes unexpectedly.) - https://f-droid.org/app/taco.scoop

**Comment by userkilled** [comment]
And the app can't be opened anymore. So I'm waiting for an update. I just don't remember the repositories that well. But at this rate I'll have to do backups. 🤭

**Comment by Iamlooker** [comment]
No @userkilled this is not the crash probably. This has been fixed and will be available in next update tomorrow.

**Comment by Iamlooker** [comment]
@klaurence can you test on this apk please
[droidify-alpha-1.zip](https://github.com/Droid-ify/client/files/12399707/droidify-alpha-1.zip)

**Comment by userkilled** [comment]
I not add repo: http://rk63tc3isr7so7ubl6q7kdxzzws7a7t6s467lbtw2ru3cwy6zu6w4jad.onion/fdroid/repo/?fingerprint=0C72C540E5841030FAE32329A1BC8747DCAC5236E4D1AAEDB67735CA7B7DD3D6

I 'ON' proxy

**Comment by Iamlooker** [comment]
> App not added this repo: http://rk63tc3isr7so7ubl6q7kdxzzws7a7t6s467lbtw2ru3cwy6zu6w4jad.onion/fdroid/repo/?fingerprint=0C72C540E5841030FAE32329A1BC8747DCAC5236E4D1AAEDB67735CA7B7DD3D6
> 
> I 'ON' proxy

Did you try this on the alpha build?

**Comment by klaurence** [comment]
@userkilled I also don't have ADB (or Shizuku for that matter), unfortunately. Thank you for the suggestion, though.

@Iamlooker The crash occurs in the alpha APK you gave.

**Comment by klaurence** [comment]
I was able in the meantime to give Scoop access to logs by using ADB. Here's the logcat for the Alpha version crashing.

```
FATAL EXCEPTION: main
Process: com.looker.droidify.alpha, PID: 9689
java.lang.IllegalStateException
	at com.looker.droidify.service.DownloadService.publishForegroundState(DownloadService.kt:369)
	at com.looker.droidify.service.DownloadService.access$publishForegroundState(DownloadService.kt:39)
	at com.looker.droidify.service.DownloadService$onCreate$2$2.emit(DownloadService.kt:152)
	at com.looker.droidify.service.DownloadService$onCreate$2$2$emit$1.invokeSuspend(DownloadService.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7012905, Dispatchers.Main]
```

**Comment by Iamlooker** [comment]
Thanks, I will fix this and release in today's release.

**Comment by laurentlbm** [comment]
It's still happening for me in v0.5.8.2

Stack trace:
```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 3845
java.lang.IllegalStateException
	at com.looker.droidify.service.DownloadService.publishForegroundState(SourceFile:209)
	at com.looker.droidify.service.DownloadService$onCreate$2$2.emit(SourceFile:1)
	at com.looker.droidify.service.DownloadService$onCreate$2$2$emit$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlin.text.RegexKt.resume(SourceFile:1)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(SourceFile:26)
	at androidx.work.Worker$2.run(SourceFile:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7979)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8b7c7ba, Dispatchers.Main]
```

**Comment by klaurence** [comment]
Curiously, it didn't crash for me in 0.5.8.2. I'll update here if it does.
