### ISSUE TITLE
[BUG] One-time crash

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#568]
**Describe the bug**
I'm not interested in this, it only happened once, and I cannot reproduce it, but I thought you'd want to know. I temporarily installed NeoStore from within Droid-ify. Installation was successful, then Droid-ify crashed.

Droid-ify 0.5.9 Patch 2 from F-droid, on Samsung Android 7.1.

```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.looker.droidify, PID: 15906
java.lang.SecurityException: Caller has no access to session 367086598
	at android.os.Parcel.readException(Parcel.java:1712)
	at android.os.Parcel.readException(Parcel.java:1662)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:304)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:388)
	at com.looker.installer.installers.session.SessionInstaller.cleanup(SourceFile)
	at com.looker.installer.InstallManager$installer$1.invokeSuspend(SourceFile:274)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5077e53, Dispatchers.Default]

```

**Comment by Iamlooker** [comment]
Persists in Patch 5?

**Comment by opk12** [comment]
Sorry, I don't know. I could never reproduce it. The logcat has no occurrence besides that one.
