### ISSUE TITLE
[BUG] Crash when tapping the Updates list while refreshing after an upgrade

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#621]
**Describe the bug**
Droid-ify crashes if I tap in the `Updates` list, while it is refreshing, after an upgrade is complete.

**To Reproduce**
    1. I open the tab `Updates`.
    2. I open `ImagePipe` and update it.
    3. I press Back to return to the `Updates` tab.
    4. The `Updates` list has an animation that makes the `ImagePipe` entry disappear.
    5. I tap the `ImagePipe` list entry while it is disappearing.
    6. Droid-ify crashes.

```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 13986
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 1
    at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
    at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
    at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:44)
    at android.database.CursorWrapper.getBlob(CursorWrapper.java:147)
    at com.looker.droidify.ui.appList.AppListAdapter.getProductItem(SourceFile:17)
    at com.looker.droidify.ui.appList.AppListAdapter$$ExternalSyntheticLambda0.onClick(SourceFile:1140)
    at android.view.View.performClick(View.java:6312)
    ...
```

**Smartphone (please complete the following information):**
Happened on Droid-ify 0.5.9 Patch 5 and 0.5.9 Patch 2, both from F-droid, on Samsung Android 7.1.

**Additional context**
Happened twice. The second crash was for `HTTP Requests Shortcuts` and said `Index -1 requested, with a size of 4` (not 1).

Happy holidays :)

**Comment by Iamlooker** [comment]
Should be fixed
