### ISSUE TITLE
[Crash] App cannot start

### ISSUE THREAD

**Issue by PatrykMis** [Droid-ify/client#627]
**Describe the bug**
App does not start either as an activity nor as a service.

**To Reproduce**
1. Install the app
2. Try to launch it or reboot the device.

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: Android 14
 - Version v0.6.0

**Stack trace**

```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
package: com.looker.droidify:600
process: com.looker.droidify
processUptime: 1952 + 285 ms

java.lang.RuntimeException: Unable to create application com.looker.droidify.MainApplication: coil.network.HttpException: lateinit property db has not been initialized
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7093)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2268)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: coil.network.HttpException: lateinit property db has not been initialized
	at com.looker.droidify.database.Database$RepositoryAdapter.putWithoutNotification$app_release(SourceFile:79)
	at com.looker.droidify.database.Database$RepositoryAdapter.put(SourceFile:21)
	at com.looker.droidify.database.Database$Helper.onVersionChange(SourceFile:49)
	at com.looker.droidify.database.Database$Helper.onUpgrade(Unknown Source:5)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:423)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
	at com.looker.droidify.MainApplication.onCreate(SourceFile:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1321)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7088)
	... 11 more

```

**Comment by PatrykMis** [comment]
Update: reinstalling the app a.k.a. clearing cache and data solves the issue. The app just can't be updated from previous stable version to v0.6.0 without this issue.

**Comment by zer0fl0w** [comment]
can confirm. same behavior for me.

**Comment by kyoyacchi** [comment]
I have the same issue, after installing 0.6.0 it can't be opened

**Comment by Iamlooker** [comment]
Sorry for the inconvenience. I will release a hotfix for this.

**Comment by Iamlooker** [comment]
Dont clear data if you haven't already. I am release a update which will fix this issue.
