### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by userkilled** [Droid-ify/client#818]
**Describe the bug**

**To Reproduce**
1. I off internet 
2. Start process add repo
3. Click to "Skip" 

**Smartphone (please complete the following information):**
 - Device: Blackview BV 6300 Pro
 - OS: Android 10
 - Version: 0.6.3

**Additional context**
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 25239
java.lang.NullPointerException
	at com.looker.droidify.ui.repository.EditRepositoryFragment.invalidateState(SourceFile:3)
	at com.looker.droidify.ui.repository.EditRepositoryFragment$onSaveRepositoryClick$1.invokeSuspend(SourceFile:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3578705, Dispatchers.Main]

**Comment by Iamlooker** [comment]
Fixed with 53df86b72a14f8dba8636ced7b8be3ebc70aa228
