### ISSUE TITLE
[Crash] Installation permission prompt acceptance.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Droid-ify/client#822]
**Describe the bug**

Allowing Droid-ify to install untrusted applications caused Package Installer to crash:

<blockQuote>

```log
FATAL EXCEPTION: main
Process: com.google.android.packageinstaller, PID: 16376
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.pm.PackageInstaller$SessionInfo.getResolvedBaseApkPath()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3783)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3923)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2444)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.pm.PackageInstaller$SessionInfo.getResolvedBaseApkPath()' on a null object reference
	at com.android.packageinstaller.PackageInstallerActivity.onCreate(PackageInstallerActivity.java:371)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1457)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
	... 12 more
```

</blockQuote>

I don't know whether the AOSP JVM needs debug symbols, nor how one would install them if so.

**To Reproduce**

1. Attempt to install https://f-droid.org/packages/us.spotco.malwarescanner/
1. After the dialog (attributed to Droid-ify, but evidently provided by the OS) to allow Droid-ify to install untrusted applications was accepted and I was taken to `com.android.settings`, Package Installer crashed, and Scoop caught the trace.

**Smartphone :**

 - Device: Fairphone FP5
 - OS: Android
 - Version: 14, build FP5.UT20.B.041.20240624

**Additional context**

I'm unable to cancel the installation, now:

https://github.com/user-attachments/assets/2191a46e-035f-4bed-9db6-e353b59ff9a9

**Comment by Iamlooker** [comment]
Was your device low on storage? Maybe the file was deleted by the os? Is this still happening? If no then please close the issue

**Comment by beedell-roke** [comment]
> https://github.com/Droid-ify/client/issues/822#issuecomment-2567111376

@Iamlooker, the symptoms reproduced until I force-stopped the application. They don't any more.

I wasn't low on storage. I have no reason to hypothesise either way whether the file was deleted or retained.

**Comment by Iamlooker** [comment]
Cool, so we can close this issue?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Droid-ify/client/issues/822#issuecomment-2567127141

@Iamlooker, yeah. Forgot to click the button.

**Comment by beedell-roke** [comment]
In retrospect, I should have elevated this to [`issuetracker.google.com/issues/new?component=190923`](https://issuetracker.google.com/issues/new?component=190923&template=841312).

**Comment by beedell-roke** [comment]
> [`#issuecomment-3337716487`](https://github.com/Droid-ify/client/issues/822#issuecomment-3337716487)

Reported to [`issuetracker.google.com/issues/450752877`](https://issuetracker.google.com/issues/450752877#comment1).
